version: "3"
services:
  fe-patients-board-2:
    image: cegekaacademy/fe-patients-board-2:1.0
    container_name: patient-fe
    restart: on-failure
    ports:
      - 5173:5173
    expose:
      - 5173
    depends_on:
      - be-patients-board-2
  be-patients-board-2:
    build:
      dockerfile: Dockerfile
    image: cegekaacademy/be-patients-board-2:1.0
    container_name: patient-be
    restart: on-failure
    ports:
      - 8090:8080
    expose:
      - 8090
    depends_on:
      - postgres_db
    networks:
      - docker-net
  postgres_db:
    image: "postgres:latest"
    restart: on-failure
    container_name: postgres_db
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=patient_board
      - POSTGRES_PASSWORD=patient_board
    networks:
      - docker-net
networks:
  docker-net:
    driver: bridge